export const bloodGroupData = [{
    bgColor : "#a4cc29ff",
    bloodGroupName: "a_pos",
    WB: "",
    PRBC: "",
    PRP: "",
    PC: "",
    FFP: "",
    CRY: "",
    LPRC: "",
    TOTAL: "",       
  },
  {
    bgColor : "#fec709ff",
    bloodGroupName: "b_pos",
    WB: "",
    PRBC: "",
    PRP: "",
    PC: "",
    FFP: "",
    CRY: "",
    LPRC: "",
    TOTAL: "",       
  },
  {
    bgColor : "#118ce7ff",
    bloodGroupName: "ab_pos",
    WB: "",
    PRBC: "",
    PRP: "",
    PC: "",
    FFP: "",
    CRY: "",
    LPRC: "",
    TOTAL: "",       
  },
  {
    bgColor : "#f15a24ff",
    bloodGroupName: "o_pos",
    WB: "",
    PRBC: "",
    PRP: "",
    PC: "",
    FFP: "",
    CRY: "",
    LPRC: "",
    TOTAL: "",       
  },
  {
    bgColor : "#c7e07bff",
    bloodGroupName: "a_neg",
    WB: "",
    PRBC: "",
    PRP: "",
    PC: "",
    FFP: "",
    CRY: "",
    LPRC: "",
    TOTAL: "",       
  },
  {
    bgColor : "#f9dc77ff",
    bloodGroupName: "b_neg",
    WB: "",
    PRBC: "",
    PRP: "",
    PC: "",
    FFP: "",
    CRY: "",
    LPRC: "",
    TOTAL: "",       
  },
  {
    bgColor : "#6fbdf7ff",
    bloodGroupName: "ab_neg",
    WB: "",
    PRBC: "",
    PRP: "",
    PC: "",
    FFP: "",
    CRY: "",
    LPRC: "",
    TOTAL: "",       
  },
  {
    bgColor : "#ffad8fff", 
    bloodGroupName: "o_neg",
    WB: "",
    PRBC: "",
    PRP: "",
    PC: "",
    FFP: "",
    CRY: "",
    LPRC: "",
    TOTAL: "",       
  },
]